# Generated by Django 5.1.2 on 2024-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_article_categorie_auteur_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='en_avant',
            field=models.BooleanField(default=False),
        ),
    ]
